"""add units, price, created_at to products

Revision ID: 8b6c48a0828d
Revises: 347e8550b938
Create Date: 2026-08-20 16:43:20.244516

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b6c48a0828d"
down_revision: str | Sequence[str] | None = "347e8550b938"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("units", sa.Integer(), server_default="0", nullable=False))
    op.add_column("products", sa.Column("price", sa.Float(), nullable=False))
    op.add_column(
        "products",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "created_at")
    op.drop_column("products", "price")
    op.drop_column("products", "units")
    # ### end Alembic commands ###
